apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "worker.name" . }}
  labels:
    {{- include "worker.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: worker
    apiGroup: ""
roleRef:
  kind: Role
  name: {{ include "worker.name" . }}
  apiGroup: rbac.authorization.k8s.io
