const {
  MATCH_ENGINE_FILTER_OUT,
  NOT_IN_PR_DIFFS,
  MATCH_IGNORE_FILE,
  DISABLED_LINE,
  DISABLED_RULE,
  IS_DUPLICATED,
  IS_USER_ACTION_SET,
  USER_ACTION_FALSE_POSITIVE
} = require('./filterReasonFlag');

const filterReasonMask = {
  NOT_VULNERABILITY_BY_ENGINE_MASK:
    MATCH_ENGINE_FILTER_OUT | DISABLED_RULE | IS_DUPLICATED | MATCH_IGNORE_FILE | DISABLED_LINE,
  NOT_VULNERABILITY_BY_USER_ACTION_MASK: USER_ACTION_FALSE_POSITIVE,
  IS_USER_ACTION_SET_MASK: IS_USER_ACTION_SET,
  IGNORE_REPORT_MASK: NOT_IN_PR_DIFFS
};

module.exports = filterReasonMask;
